Repository cloudsmartio/environment-cloudsmart-cluster1-dev, pull requests merged in 2020-02, with the labels that each got.

#19 feat(config): upgrade configuration
  OWNERS
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
  jx-requirements.yml
  systems/acme/Chart.yaml
  systems/velero/values.tmpl.yaml
Labels: approved, size/M

#20 feat(config): upgrade configuration
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
  jx-requirements.yml
Labels: approved, size/S

#21 Add jx-app-ui 0.1.36
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/requirements.yaml
Labels: approved, size/XS

#22 Update values.yaml
  env/jx-app-ui/values.yaml
Labels: size/XS
