Repository cloudsmartio/environment-cloudsmart-cluster1-dev, pull requests merged in 2020-01, with the labels that each got.

#2 chore(deps): bump https://github.com/cloudsmartio/dex-client-poc.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/cloudsmartio-dex-client-poc-sr.yaml
Labels: size/M, updatebot

#4 Add jx-app-replicator 1.0.16
  env/jx-app-replicator/README.MD
  env/jx-app-replicator/templates/app.yaml
  env/requirements.yaml
Labels: size/S

#5 feat(config): upgrade configuration
  env/jxboot-resources/values.tmpl.yaml
  env/values.tmpl.yaml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
  jx-requirements.yml
  kubeProviders/eks/templates/vault_cf_tmpl.yml
  systems/acme/Chart.yaml
  systems/jx-auth/Chart.yaml
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
  systems/jx-auth/templates/jx-auth-configmap.yaml
Labels: size/M

#6 chore(deps): bump https://github.com/cloudsmartio/application-root.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/cloudsmartio-application-root-sr.yaml
Labels: size/S, updatebot

#7 chore(deps): bump https://github.com/cloudsmartio/agile-project-manager.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/cloudsmartio-agile-project-manager-sr.yaml
Labels: size/S, updatebot

#8 feat(config): upgrade configuration
  OWNERS
  env/jxboot-resources/values.tmpl.yaml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
  jx-requirements.yml
  kubeProviders/eks/templates/irsa.tmpl.yaml
  systems/acme/Chart.yaml
  systems/external-dns/values.tmpl.yaml
Labels: approved, size/M

#9 Enable Velero
  jx-requirements.yml
Labels: size/XS

#10 Add Velero bucket
  jx-requirements.yml
Labels: size/XS

#11 Add jx-app-ui 0.1.26
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/jx-app-ui/values.yaml
  env/requirements.yaml
Labels: approved, size/M

#12 Remove properties that conflict with jx version
  jx-requirements.yml
Labels: size/XS

#13 Delete jx-app-ui
  env/requirements.yaml
Labels: approved, size/XS

#14 chore(deps): bump https://github.com/cloudsmartio/gitprovider-sync-agent.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/cloudsmartio-gitprovider-sync-agent-sr.yaml
Labels: size/M, updatebot

#15 chore(deps): bump https://github.com/cloudsmartio/notifications-service.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/cloudsmartio-notifications-service-sr.yaml
Labels: size/S, updatebot

#16 chore(deps): bump dependency versions
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/cloudsmartio-agile-project-manager-composite-sr.yaml
  repositories/templates/cloudsmartio-agile-project-manager-frontend-sr.yaml
Labels: size/M, updatebot

#17 feat(config): upgrade configuration
  OWNERS
  env/lighthouse/values.tmpl.yaml
  env/prow/values.tmpl.yaml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x.yml
  jx-requirements.yml
  systems/acme/Chart.yaml
  systems/velero/values.tmpl.yaml
Labels: approved, size/M

#18 chore(deps): bump https://github.com/cloudsmartio/authservice.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/cloudsmartio-authservice-sr.yaml
Labels: size/S, updatebot
